<?php

namespace FelipeReisDev\PhpBoost\Core\Services;

class GuidelineGenerator
{
    private $projectInfo;
    private $templatesPath;
    private $customTemplatesPath;
    private $projectRoot;
    private $localeManager;

    public function __construct(array $projectInfo, $templatesPath = null, $projectRoot = null, $locale = null)
    {
        $this->projectInfo = $projectInfo;
        $this->templatesPath = $templatesPath ?: __DIR__ . '/../Templates';
        $this->projectRoot = $projectRoot ?: getcwd();
        $this->customTemplatesPath = $this->projectRoot . '/.php-boost/templates';
        $this->localeManager = new LocaleManager($locale);
    }

    public function setLocale($locale)
    {
        $this->localeManager->setLocale($locale);
    }

    public function getLocale()
    {
        return $this->localeManager->getLocale();
    }

    public function generateClaudeMd()
    {
        $sections = [];

        $sections[] = "# Claude Development Guidelines for {$this->projectInfo['name']}";
        $sections[] = "\n<!-- AUTO-GENERATED by PHP Boost -->";
        $sections[] = "<!-- Last updated: " . date('Y-m-d H:i:s') . " -->\n";

        $sections[] = $this->generateProjectInfo();
        $sections[] = $this->generatePhpSection();
        $sections[] = $this->generateFrameworkSection();
        $sections[] = $this->generateDatabaseSection();
        $sections[] = $this->generateEnvironmentSection();
        $sections[] = $this->generatePackagesSection();
        $sections[] = $this->generateTestingSection();
        $sections[] = $this->generateProjectStructureSection();

        $sections[] = "\n<!-- END AUTO-GENERATED -->";
        $sections[] = "<!-- Custom sections below are preserved during updates -->\n";

        return implode("\n", array_filter($sections));
    }

    public function generateAgentsMd()
    {
        $sections = [];

        $sections[] = "# AI Agent Guidelines for {$this->projectInfo['name']}";
        $sections[] = "\n<!-- AUTO-GENERATED by PHP Boost -->";
        $sections[] = "<!-- Last updated: " . date('Y-m-d H:i:s') . " -->\n";

        $sections[] = $this->generateProjectInfo();
        $sections[] = $this->generateBuildCommands();
        $sections[] = $this->generateTestCommands();
        $sections[] = $this->generateCodeStyle();
        $sections[] = $this->generatePhpSection();
        $sections[] = $this->generateFrameworkSection();

        $sections[] = "\n<!-- END AUTO-GENERATED -->";

        return implode("\n", array_filter($sections));
    }

    private function generateProjectInfo()
    {
        $info = [];
        $info[] = "## Project Information\n";
        $info[] = "- **Project Name:** {$this->projectInfo['name']}";
        $info[] = "- **Framework:** {$this->projectInfo['framework']['name']} {$this->projectInfo['framework']['version']}";
        $info[] = "- **PHP Version:** {$this->projectInfo['php']['runtime']} (Constraint: {$this->projectInfo['php']['constraint']})";
        
        if (!empty($this->projectInfo['database'])) {
            $info[] = "- **Database:** {$this->projectInfo['database']}";
        }
        
        if (!empty($this->projectInfo['environment'])) {
            $info[] = "- **Environment:** {$this->projectInfo['environment']}";
        }
        
        if (!empty($this->projectInfo['tests']['framework'])) {
            $info[] = "- **Test Framework:** {$this->projectInfo['tests']['framework']} ({$this->projectInfo['tests']['count']} tests)";
        }

        return implode("\n", $info);
    }

    private function generatePhpSection()
    {
        $phpVersion = $this->projectInfo['php']['constraint'];
        $majorMinor = $this->extractMajorMinor($phpVersion);
        
        $templateFile = $this->templatesPath . "/Php/php{$majorMinor}.php";
        return $this->loadTemplate($templateFile);
    }

    private function generateFrameworkSection()
    {
        $framework = strtolower($this->projectInfo['framework']['name']);
        
        if ($framework === 'standalone') {
            return '';
        }

        $version = $this->projectInfo['framework']['version'];
        $majorVersion = (int) explode('.', $version)[0];
        
        $templateFile = $this->templatesPath . "/Framework/" . ucfirst($framework) . "/{$framework}{$majorVersion}.php";
        return $this->loadTemplate($templateFile);
    }

    private function generateDatabaseSection()
    {
        if (empty($this->projectInfo['database'])) {
            return '';
        }

        $database = strtolower($this->projectInfo['database']);
        $templateFile = $this->templatesPath . "/Database/{$database}.php";
        return $this->loadTemplate($templateFile);
    }

    private function generateEnvironmentSection()
    {
        if (empty($this->projectInfo['environment'])) {
            return '';
        }

        $env = strtolower($this->projectInfo['environment']);
        $templateFile = $this->templatesPath . "/Environment/{$env}.php";
        return $this->loadTemplate($templateFile);
    }

    private function generatePackagesSection()
    {
        if (empty($this->projectInfo['packages'])) {
            return '';
        }

        $sections = [];
        $sections[] = "\n## Installed Packages\n";

        foreach ($this->projectInfo['packages'] as $package => $version) {
            $packageName = $this->extractPackageName($package);
            $templateFile = $this->templatesPath . "/Packages/{$packageName}.php";

            $templateContent = $this->loadTemplate($templateFile);
            if ($templateContent !== '') {
                $sections[] = $templateContent;
            } else {
                $sections[] = "- **{$package}:** {$version}";
            }
        }

        return implode("\n", $sections);
    }

    private function generateTestingSection()
    {
        if (empty($this->projectInfo['tests']['framework'])) {
            return '';
        }

        $framework = strtolower($this->projectInfo['tests']['framework']);
        $count = $this->projectInfo['tests']['count'];

        $sections = [];
        $sections[] = "\n## Testing Guidelines\n";
        $sections[] = "- **Framework:** {$this->projectInfo['tests']['framework']}";
        $sections[] = "- **Test Count:** {$count} tests";
        $sections[] = "- **Command:** `" . $this->getTestCommand() . "`";
        
        if ($framework === 'pest') {
            $sections[] = "\n### Pest Testing";
            $sections[] = "- Use descriptive test names with `it()` or `test()`";
            $sections[] = "- Organize tests with `describe()` blocks";
            $sections[] = "- Use `beforeEach()` and `afterEach()` for setup/teardown";
            $sections[] = "- Leverage dataset providers for parameterized tests";
            $sections[] = "- Use expectation API: `expect()->toBe()`, `toBeInstanceOf()`, etc.";
        } else {
            $sections[] = "\n### PHPUnit Testing";
            $sections[] = "- Follow `testMethodName` or `test_method_name` convention";
            $sections[] = "- Use `setUp()` and `tearDown()` for test fixtures";
            $sections[] = "- One assertion concept per test method";
            $sections[] = "- Use data providers for parameterized tests";
            $sections[] = "- Prefer `assertSame()` over `assertEquals()` when possible";
        }

        return implode("\n", $sections);
    }

    private function generateProjectStructureSection()
    {
        if (empty($this->projectInfo['structure'])) {
            return '';
        }

        $sections = [];
        $sections[] = "\n## Project Structure\n";
        $sections[] = "```";
        
        foreach ($this->projectInfo['structure'] as $dir) {
            $sections[] = $dir;
        }
        
        $sections[] = "```";

        return implode("\n", $sections);
    }

    private function generateBuildCommands()
    {
        $framework = strtolower($this->projectInfo['framework']['name']);
        
        $sections = [];
        $sections[] = "\n## Build Commands\n";

        if ($framework === 'laravel' || $framework === 'lumen') {
            $sections[] = "```bash";
            $sections[] = "composer install";
            $sections[] = "php artisan config:clear";
            $sections[] = "php artisan cache:clear";
            
            if ($framework === 'laravel') {
                $sections[] = "php artisan route:clear";
                $sections[] = "php artisan view:clear";
            }
            
            $sections[] = "```";
        } else {
            $sections[] = "```bash";
            $sections[] = "composer install";
            $sections[] = "composer dump-autoload";
            $sections[] = "```";
        }

        return implode("\n", $sections);
    }

    private function generateTestCommands()
    {
        $sections = [];
        $sections[] = "\n## Test Commands\n";
        $sections[] = "```bash";
        $sections[] = $this->getTestCommand();
        $sections[] = "```";

        return implode("\n", $sections);
    }

    private function generateCodeStyle()
    {
        $sections = [];
        $sections[] = "\n## Code Style\n";
        $sections[] = "- **PSR-12** compliance required";
        $sections[] = "- **Classes:** PascalCase";
        $sections[] = "- **Methods:** camelCase";
        $sections[] = "- **Constants:** UPPER_SNAKE_CASE";
        $sections[] = "- **Properties:** camelCase";
        $sections[] = "- Type hints required for parameters and return types";
        $sections[] = "- Visibility modifiers required for all methods and properties";

        return implode("\n", $sections);
    }

    private function getTestCommand()
    {
        $framework = strtolower($this->projectInfo['tests']['framework'] ?? 'phpunit');
        
        if ($framework === 'pest') {
            return './vendor/bin/pest';
        }
        
        return './vendor/bin/phpunit';
    }

    private function extractMajorMinor($version)
    {
        preg_match('/(\d+)\.(\d+)/', $version, $matches);
        
        if (isset($matches[1], $matches[2])) {
            return $matches[1] . $matches[2];
        }
        
        return '74';
    }

    private function extractPackageName($package)
    {
        if (strpos($package, '/') !== false) {
            $parts = explode('/', $package);
            return end($parts);
        }
        
        return $package;
    }

    private function loadTemplate($templateFile)
    {
        $localizedTemplate = $this->localeManager->resolveTemplatePath($templateFile);
        
        $customTemplate = $this->getCustomTemplatePath($localizedTemplate);
        
        if (file_exists($customTemplate)) {
            $content = include $customTemplate;
            
            if (file_exists($localizedTemplate)) {
                $defaultContent = include $localizedTemplate;
                return $this->mergeTemplateContents($content, $defaultContent);
            }
            
            return $content;
        }
        
        if (!file_exists($localizedTemplate)) {
            return '';
        }

        return include $localizedTemplate;
    }

    private function getCustomTemplatePath($defaultTemplatePath)
    {
        $relativePath = str_replace($this->templatesPath . '/', '', $defaultTemplatePath);
        return $this->customTemplatesPath . '/' . $relativePath;
    }

    private function mergeTemplateContents($customContent, $defaultContent)
    {
        if (is_string($customContent) && is_string($defaultContent)) {
            if (strpos($customContent, '<!-- MERGE:APPEND -->') !== false) {
                return str_replace('<!-- MERGE:APPEND -->', $defaultContent . "\n\n", $customContent);
            }
            
            if (strpos($customContent, '<!-- MERGE:PREPEND -->') !== false) {
                return str_replace('<!-- MERGE:PREPEND -->', "\n\n" . $defaultContent, $customContent);
            }
        }
        
        return $customContent;
    }
}
