<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use FelipeReisDev\PhpBoost\Core\Services\GuidelineGenerator;

class GuidelineGeneratorTest extends TestCase
{
    private $projectInfo;

    protected function setUp(): void
    {
        parent::setUp();
        
        $this->projectInfo = [
            'name' => 'test/project',
            'framework' => [
                'name' => 'Laravel',
                'version' => '8.75.0'
            ],
            'php' => [
                'runtime' => '7.4.33',
                'constraint' => '^7.4'
            ],
            'database' => 'mysql',
            'environment' => 'herd',
            'tests' => [
                'framework' => 'PHPUnit',
                'count' => 42
            ],
            'packages' => [
                'laravel/sanctum' => '^2.15'
            ],
            'structure' => [
                'app/',
                'config/',
                'database/',
            ]
        ];
    }

    public function testGenerateClaudeMd()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateClaudeMd();
        
        $this->assertStringContainsString('# Claude Development Guidelines', $content);
        $this->assertStringContainsString('AUTO-GENERATED by PHP Boost', $content);
        $this->assertStringContainsString('END AUTO-GENERATED', $content);
        $this->assertStringContainsString('test/project', $content);
        $this->assertStringContainsString('Laravel 8.75.0', $content);
        $this->assertStringContainsString('PHP 7.4', $content);
    }

    public function testGenerateAgentsMd()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateAgentsMd();
        
        $this->assertStringContainsString('# AI Agent Guidelines', $content);
        $this->assertStringContainsString('AUTO-GENERATED by PHP Boost', $content);
        $this->assertStringContainsString('END AUTO-GENERATED', $content);
        $this->assertStringContainsString('test/project', $content);
        $this->assertStringContainsString('Installed Packages', $content);
        $this->assertStringContainsString('laravel/sanctum', $content);
    }

    public function testContentIncludesProjectInfo()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateClaudeMd();
        
        $this->assertStringContainsString('**Framework:** Laravel 8.75.0', $content);
        $this->assertStringContainsString('**PHP Version:** 7.4.33', $content);
        $this->assertStringContainsString('**Database:** mysql', $content);
        $this->assertStringContainsString('**Environment:** herd', $content);
        $this->assertStringContainsString('**Test Framework:** PHPUnit (42 tests)', $content);
    }

    public function testContentIncludesPackages()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateClaudeMd();
        
        $this->assertStringContainsString('Installed Packages', $content);
        $this->assertStringContainsString('laravel/sanctum', $content);
    }

    public function testContentIncludesProjectStructure()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateClaudeMd();
        
        $this->assertStringContainsString('Project Structure', $content);
        $this->assertStringContainsString('app/', $content);
        $this->assertStringContainsString('config/', $content);
    }

    public function testGenerateClaudeMdLoadsLocalizedTemplates()
    {
        $generator = new GuidelineGenerator($this->projectInfo);
        $content = $generator->generateClaudeMd();

        $this->assertStringContainsString('## PHP 7.4 Best Practices', $content);
        $this->assertStringContainsString('## Laravel 8 Best Practices', $content);
        $this->assertStringContainsString('## MySQL Best Practices', $content);
        $this->assertStringContainsString('## Laravel Herd Development Environment', $content);
    }
}
