<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use FelipeReisDev\PhpBoost\Core\Services\GuidelineWriter;

class GuidelineWriterTest extends TestCase
{
    private $tempDir;
    private $writer;

    protected function setUp(): void
    {
        parent::setUp();
        
        $this->tempDir = sys_get_temp_dir() . '/php-boost-test-' . uniqid();
        mkdir($this->tempDir);
        
        $this->writer = new GuidelineWriter($this->tempDir);
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        
        $this->cleanupDirectory($this->tempDir);
        
        if (is_dir($this->tempDir)) {
            rmdir($this->tempDir);
        }
    }

    private function cleanupDirectory($dir)
    {
        if (!is_dir($dir)) {
            return;
        }
        
        $files = array_diff(scandir($dir), ['.', '..']);
        
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            
            if (is_dir($path)) {
                $this->cleanupDirectory($path);
                rmdir($path);
            } else {
                unlink($path);
            }
        }
    }

    public function testWriteClaudeMd()
    {
        $content = "# Test Content\n\nThis is test content.";
        
        $result = $this->writer->writeClaudeMd($content);
        
        $this->assertTrue($result);
        $this->assertFileExists($this->tempDir . '/CLAUDE.md');
        
        $written = file_get_contents($this->tempDir . '/CLAUDE.md');
        $this->assertEquals($content, $written);
    }

    public function testWriteAgentsMd()
    {
        $content = "# Test Agents\n\nThis is agents content.";
        
        $result = $this->writer->writeAgentsMd($content);
        
        $this->assertTrue($result);
        $this->assertFileExists($this->tempDir . '/AGENTS.md');
        
        $written = file_get_contents($this->tempDir . '/AGENTS.md');
        $this->assertEquals($content, $written);
    }

    public function testBackupCreatedOnOverwrite()
    {
        $originalContent = "# Original\n\nOriginal content.";
        file_put_contents($this->tempDir . '/CLAUDE.md', $originalContent);
        
        $newContent = "# Updated\n\nUpdated content.";
        $this->writer->writeClaudeMd($newContent);
        
        $this->assertTrue($this->writer->hasBackups('CLAUDE.md'));
        
        $backupPath = $this->writer->getBackupPath();
        $this->assertDirectoryExists($backupPath);
    }

    public function testMergePreservesCustomContent()
    {
        $originalContent = <<<'MD'
# Test
<!-- AUTO-GENERATED by PHP Boost -->
Generated section
<!-- END AUTO-GENERATED -->
Custom section that should be preserved
MD;
        
        file_put_contents($this->tempDir . '/CLAUDE.md', $originalContent);
        
        $newContent = <<<'MD'
# Test
<!-- AUTO-GENERATED by PHP Boost -->
Updated generated section
<!-- END AUTO-GENERATED -->
MD;
        
        $this->writer->writeClaudeMd($newContent);
        
        $result = file_get_contents($this->tempDir . '/CLAUDE.md');
        
        $this->assertStringContainsString('Updated generated section', $result);
        $this->assertStringContainsString('Custom section that should be preserved', $result);
    }

    public function testGetLatestBackup()
    {
        file_put_contents($this->tempDir . '/CLAUDE.md', 'Content 1');
        $this->writer->writeClaudeMd('Content 2');
        
        sleep(1);
        
        $this->writer->writeClaudeMd('Content 3');
        
        $latestBackup = $this->writer->getLatestBackup('CLAUDE.md');
        
        $this->assertNotNull($latestBackup);
        $this->assertFileExists($latestBackup);
    }
}
